name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  NODE_OPTIONS: "--max-old-space-size=4096"
  # For Google Cloud Artifact Registry
  IMAGE: us-east1-docker.pkg.dev/dev-deepsky/deepsky-docker/nui
  REGISTRY: us-east1-docker.pkg.dev

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    permissions:
      contents: read

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Authenticate to Google Cloud
        if: github.event_name != 'pull_request'
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.DEEPSKY_DEV_GSA_CREDENTIALS }}

      - name: Configure docker for Google Cloud
        if: github.event_name != 'pull_request'
        run: gcloud auth configure-docker ${{ env.REGISTRY }} --quiet

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE }}
          tags: |
            type=raw,value=latest

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: VERSION=edge-${{ github.sha }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

